#pragma once

#include <unordered_map>
#include <string>

namespace nsn {
	enum struct keys : int {
		null = '\0',
		ctrl_a = 0x1000,
		ctrl_b,
		ctrl_c,
		ctrl_d,
		ctrl_e,
		ctrl_f,
		ctrl_g,
		ctrl_h,
		ctrl_i,
		ctrl_j,
		ctrl_k,
		ctrl_l,
		ctrl_m,
		ctrl_n,
		ctrl_o,
		ctrl_p,
		ctrl_q,
		ctrl_r,
		ctrl_s,
		ctrl_t,
		ctrl_u,
		ctrl_v,
		ctrl_w,
		ctrl_x,
		ctrl_y,
		ctrl_z,
		ctrl_alt_a,
		ctrl_alt_b,
		ctrl_alt_c,
		ctrl_alt_d,
		ctrl_alt_e,
		ctrl_alt_f,
		ctrl_alt_g,
		ctrl_alt_h,
		ctrl_alt_i,
		ctrl_alt_j,
		ctrl_alt_k,
		ctrl_alt_l,
		ctrl_alt_m,
		ctrl_alt_n,
		ctrl_alt_o,
		ctrl_alt_p,
		ctrl_alt_q,
		ctrl_alt_r,
		ctrl_alt_s,
		ctrl_alt_t,
		ctrl_alt_u,
		ctrl_alt_v,
		ctrl_alt_w,
		ctrl_alt_x,
		ctrl_alt_y,
		ctrl_alt_z,
		alt_space,
		alt_exclamation_mark,
		alt_quotes,
		alt_hashtag,
		alt_dollar,
		alt_percent,
		alt_ampersand,
		alt_apostrophe,
		alt_left_parenthesis,
		alt_right_parenthesis,
		alt_star,
		alt_plus,
		alt_comma,
		alt_dash,
		alt_dot,
		alt_slash,
		alt_zero,
		alt_one,
		alt_two,
		alt_three,
		alt_four,
		alt_five,
		alt_six,
		alt_seven,
		alt_eight,
		alt_nine,
		alt_colon,
		alt_semicolon,
		alt_less_than,
		alt_equal,
		alt_greater_than,
		alt_question_mark,
		alt_strudel,
		alt_A,
		alt_B,
		alt_C,
		alt_D,
		alt_E,
		alt_F,
		alt_G,
		alt_H,
		alt_I,
		alt_J,
		alt_K,
		alt_L,
		alt_M,
		alt_N,
		alt_O,
		alt_P,
		alt_Q,
		alt_R,
		alt_S,
		alt_T,
		alt_U,
		alt_V,
		alt_W,
		alt_X,
		alt_Y,
		alt_Z,
		alt_left_bracket,
		alt_backslash,
		alt_right_bracket,
		alt_caret,
		alt_underscore,
		alt_grave,
		alt_a,
		alt_b,
		alt_c,
		alt_d,
		alt_e,
		alt_f,
		alt_g,
		alt_h,
		alt_i,
		alt_j,
		alt_k,
		alt_l,
		alt_m,
		alt_n,
		alt_o,
		alt_p,
		alt_q,
		alt_r,
		alt_s,
		alt_t,
		alt_u,
		alt_v,
		alt_w,
		alt_x,
		alt_y,
		alt_z,
		alt_left_brace,
		alt_pipe,
		alt_right_brace,
		alt_tilde,
		alt_backspace,
		alt_tab = nsn::keys::ctrl_alt_i,
		alt_enter = nsn::keys::ctrl_alt_m,
		space = ' ',
		exclamation_mark = '!',
		quotes = '\"',
		hashtag = '#',
		dollar = '$',
		percent = '%',
		ampersand = '&',
		apostrophe = '\'',
		left_parenthesis = '(',
		right_parenthesis = ')',
		star = '*',
		plus = '+',
		comma = ',',
		dash = '-',
		dot = '.',
		slash = '/',
		zero = '0',
		one = '1',
		two = '2',
		three = '3',
		four = '4',
		five = '5',
		six = '6',
		seven = '7',
		eight = '8',
		nine = '9',
		colon = ':',
		semicolon = ';',
		less_than = '<',
		equal = '=',
		greater_than = '>',
		question_mark = '?',
		strudel = '@',
		A = 'A',
		B = 'B',
		C = 'C',
		D = 'D',
		E = 'E',
		F = 'F',
		G = 'G',
		H = 'H',
		I = 'I',
		J = 'J',
		K = 'K',
		L = 'L',
		M = 'M',
		N = 'N',
		O = 'O',
		P = 'P',
		Q = 'Q',
		R = 'R',
		S = 'S',
		T = 'T',
		U = 'U',
		V = 'V',
		W = 'W',
		X = 'X',
		Y = 'Y',
		Z = 'Z',
		left_bracket = '[',
		backslash = '\\',
		right_bracket = ']',
		caret = '^',
		underscore = '_',
		grave = '`',
		a = 'a',
		b = 'b',
		c = 'c',
		d = 'd',
		e = 'e',
		f = 'f',
		g = 'g',
		h = 'h',
		i = 'i',
		j = 'j',
		k = 'k',
		l = 'l',
		m = 'm',
		n = 'n',
		o = 'o',
		p = 'p',
		q = 'q',
		r = 'r',
		s = 's',
		t = 't',
		u = 'u',
		v = 'v',
		w = 'w',
		x = 'x',
		y = 'y',
		z = 'z',
		left_brace = '{',
		pipe = '|',
		right_brace = '}',
		tilde = '~',
		backspace,
		numpad_zero = '0',
		numpad_one = '1',
		numpad_two = '2',
		numpad_three = '3',
		numpad_four = '4',
		numpad_five = '5',
		numpad_six = '6',
		numpad_seven = '7',
		numpad_eight = '8',
		numpad_nine = '9',
		numpad_dot = '.',
		f1 = 0x2000,
		f2,
		f3,
		f4,
		f5,
		f6,
		f7,
		f8,
		f9,
		f10,
		f11,
		f12,
		f13,
		f14,
		f15,
		f16,
		f17,
		f18,
		f19,
		f20,
		f21,
		f22,
		f23,
		f24,
		pause,
		tab = nsn::keys::ctrl_i,
		enter = nsn::keys::ctrl_m,
		insert = nsn::keys::numpad_zero,
		del = nsn::keys::numpad_dot,
		page_up = nsn::keys::numpad_nine,
		page_down = nsn::keys::numpad_three,
		up = nsn::keys::numpad_eight,
		down = nsn::keys::numpad_two,
		right = nsn::keys::numpad_six,
		left = nsn::keys::numpad_four,
		end = nsn::keys::numpad_one,
		home = nsn::keys::numpad_seven,
		unknown = 0x3000,
	};

	std::unordered_map<std::string, nsn::keys> key_strings = {
		{ "ctrl_a", nsn::keys::ctrl_a },
		{ "ctrl_b", nsn::keys::ctrl_b },
		{ "ctrl_c", nsn::keys::ctrl_c },
		{ "ctrl_d", nsn::keys::ctrl_d },
		{ "ctrl_e", nsn::keys::ctrl_e },
		{ "ctrl_f", nsn::keys::ctrl_f },
		{ "ctrl_g", nsn::keys::ctrl_g },
		{ "ctrl_h", nsn::keys::ctrl_h },
		{ "ctrl_i", nsn::keys::ctrl_i },
		{ "ctrl_j", nsn::keys::ctrl_j },
		{ "ctrl_k", nsn::keys::ctrl_k },
		{ "ctrl_l", nsn::keys::ctrl_l },
		{ "ctrl_m", nsn::keys::ctrl_m },
		{ "ctrl_n", nsn::keys::ctrl_n },
		{ "ctrl_o", nsn::keys::ctrl_o },
		{ "ctrl_p", nsn::keys::ctrl_p },
		{ "ctrl_q", nsn::keys::ctrl_q },
		{ "ctrl_r", nsn::keys::ctrl_r },
		{ "ctrl_s", nsn::keys::ctrl_s },
		{ "ctrl_t", nsn::keys::ctrl_t },
		{ "ctrl_u", nsn::keys::ctrl_u },
		{ "ctrl_v", nsn::keys::ctrl_v },
		{ "ctrl_w", nsn::keys::ctrl_w },
		{ "ctrl_x", nsn::keys::ctrl_x },
		{ "ctrl_y", nsn::keys::ctrl_y },
		{ "ctrl_z", nsn::keys::ctrl_z },
		
		{ "ctrl_alt_a", nsn::keys::ctrl_alt_a },
		{ "ctrl_alt_b", nsn::keys::ctrl_alt_b },
		{ "ctrl_alt_c", nsn::keys::ctrl_alt_c },
		{ "ctrl_alt_d", nsn::keys::ctrl_alt_d },
		{ "ctrl_alt_e", nsn::keys::ctrl_alt_e },
		{ "ctrl_alt_f", nsn::keys::ctrl_alt_f },
		{ "ctrl_alt_g", nsn::keys::ctrl_alt_g },
		{ "ctrl_alt_h", nsn::keys::ctrl_alt_h },
		{ "ctrl_alt_i", nsn::keys::ctrl_alt_i },
		{ "ctrl_alt_j", nsn::keys::ctrl_alt_j },
		{ "ctrl_alt_k", nsn::keys::ctrl_alt_k },
		{ "ctrl_alt_l", nsn::keys::ctrl_alt_l },
		{ "ctrl_alt_m", nsn::keys::ctrl_alt_m },
		{ "ctrl_alt_n", nsn::keys::ctrl_alt_n },
		{ "ctrl_alt_o", nsn::keys::ctrl_alt_o },
		{ "ctrl_alt_p", nsn::keys::ctrl_alt_p },
		{ "ctrl_alt_q", nsn::keys::ctrl_alt_q },
		{ "ctrl_alt_r", nsn::keys::ctrl_alt_r },
		{ "ctrl_alt_s", nsn::keys::ctrl_alt_s },
		{ "ctrl_alt_t", nsn::keys::ctrl_alt_t },
		{ "ctrl_alt_u", nsn::keys::ctrl_alt_u },
		{ "ctrl_alt_v", nsn::keys::ctrl_alt_v },
		{ "ctrl_alt_w", nsn::keys::ctrl_alt_w },
		{ "ctrl_alt_x", nsn::keys::ctrl_alt_x },
		{ "ctrl_alt_y", nsn::keys::ctrl_alt_y },
		{ "ctrl_alt_z", nsn::keys::ctrl_alt_z },

		{ "alt_space", nsn::keys::alt_space },
		{ "alt_exclamation_mark", nsn::keys::alt_exclamation_mark },
		{ "alt_quotes", nsn::keys::alt_quotes },
		{ "alt_hashtag", nsn::keys::alt_hashtag },
		{ "alt_dollar", nsn::keys::alt_dollar },
		{ "alt_percent", nsn::keys::alt_percent },
		{ "alt_ampersand", nsn::keys::alt_ampersand },
		{ "alt_apostrophe", nsn::keys::alt_apostrophe },
		{ "alt_left_parenthesis", nsn::keys::alt_left_parenthesis },
		{ "alt_right_parenthesis", nsn::keys::alt_right_parenthesis },
		{ "alt_star", nsn::keys::alt_star },
		{ "alt_plus", nsn::keys::alt_plus },
		{ "alt_comma", nsn::keys::alt_comma },
		{ "alt_dash", nsn::keys::alt_dash },
		{ "alt_dot", nsn::keys::alt_dot },
		{ "alt_slash", nsn::keys::alt_slash },
		
		{ "space", nsn::keys::space },
		{ "exclamation_mark", nsn::keys::exclamation_mark },
		{ "quotes", nsn::keys::quotes },
		{ "hashtag", nsn::keys::hashtag },
		{ "dollar", nsn::keys::dollar },
		{ "percent", nsn::keys::percent },
		{ "ampersand", nsn::keys::ampersand },
		{ "apostrophe", nsn::keys::apostrophe },
		{ "left_parenthesis", nsn::keys::left_parenthesis },
		{ "right_parenthesis", nsn::keys::right_parenthesis },
		{ "star", nsn::keys::star },
		{ "plus", nsn::keys::plus },
		{ "comma", nsn::keys::comma },
		{ "dash", nsn::keys::dash },
		{ "dot", nsn::keys::dot },
		{ "slash", nsn::keys::slash },
		{ "zero", nsn::keys::zero },
		{ "one", nsn::keys::one },
		{ "two", nsn::keys::two },
		{ "three", nsn::keys::three },
		{ "four", nsn::keys::four },
		{ "five", nsn::keys::five },
		{ "six", nsn::keys::six },
		{ "seven", nsn::keys::seven },
		{ "eight", nsn::keys::eight },
		{ "nine", nsn::keys::nine },

		{ "f1", nsn::keys::f1 },
		{ "f2", nsn::keys::f2 },
		{ "f3", nsn::keys::f3 },
		{ "f4", nsn::keys::f4 },
		{ "f5", nsn::keys::f5 },
		{ "f6", nsn::keys::f6 },
		{ "f7", nsn::keys::f7 },
		{ "f8", nsn::keys::f8 },
		{ "f9", nsn::keys::f9 },
		{ "f10", nsn::keys::f10 },
		{ "f11", nsn::keys::f11 },
		{ "f12", nsn::keys::f12 },

		{ "pause", nsn::keys::pause },
		{ "tab", nsn::keys::tab },
		{ "enter", nsn::keys::enter },
		{ "insert", nsn::keys::insert },
		{ "del", nsn::keys::del },
		{ "page_up", nsn::keys::page_up },
		{ "page_down", nsn::keys::page_down },
		{ "up", nsn::keys::up },
		{ "down", nsn::keys::down },
		{ "left", nsn::keys::left },
		{ "right", nsn::keys::right },
		{ "home", nsn::keys::home },
		{ "end", nsn::keys::end },

		{ "unknown", nsn::keys::unknown }
	};
}